server.port: 7001

spring:
  data:
    mongodb:
      database: profiles-db
      host: localhost
      port: 27017

logging:
  level:
    root: INFO
    com.pankaj.onlinecv.profile: INFO
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
